# Numpy in Python

In [3]:
  #Create 1D array

import numpy as np

arry = np.array([1, 2, 3, 4, 5])
print(arry)
print(type(arry))
print(arry.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [5]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [6]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2.shape

(2, 5)

In [7]:
array3 = np.arange(0,10,2).reshape(5,1)
array3

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
array3.dtype

dtype('int64')

In [12]:
array3.itemsize

8

In [13]:
array3.ndim

2

In [14]:
array3.size

5

In [21]:
# Numpy Vectorized Operations

array1 = np.array([1,2,3,4,5])
array2 = np.array([10,20,30,40,50])

print ("Addition:", array1 + array2)


#Element wise opeartions

print ("Substraction:", array1 - array2)
print ("Multiplication:", array1 * array2)
print ("Division:", array1 / array2)



Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [24]:
#universal function

print("Square root:" ,np.sqrt(array2))
print("Exponent:" ,np.exp(array2))
print("Sin:" ,np.sin(array2))

Square root: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
Exponent: [2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
Sin: [-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]


In [44]:
# Array Slicing and Indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n", arr )
print(arr[0][2],arr[2][3])


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3 12


In [45]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [47]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [48]:
#Modify array elements

arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [49]:
#Modify array elements

arr[0,1:] = 100
print(arr)

[[100 100 100 100]
 [  5   6   7   8]
 [  9  10  11  12]]


In [52]:
#Statistical concepts - Normalization

data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data -  mean)/ std_dev

print("Normalized Data: ", normalized_data)

Normalized Data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [53]:
median = np.median(data)
variance = np.var(data)

 #Logical operations

data2 = np.array([1,2,3,4,5,6,7,8,9,10])
data2[(data2>=5) & (data2<=8)]

# PANDAS- DataFrame and Series

In [61]:
 import pandas as pd

In [62]:
# Series 1D-array that can hold any datatype

data = [1,2,3,4,5]
series = pd.Series(data)
print("Series \n",series)

Series 
 0    1
1    2
2    3
3    4
4    5
dtype: int64


In [63]:
#Create a series from dictionary
data_dict = {'a':1,'b':2,'c':3}
series_dict = pd.Series(data_dict)
print(series_dict)

a    1
b    2
c    3
dtype: int64


In [65]:
data = [10,20,30]
index = ['a','b','c']

pd.Series(data,index=index)


a    10
b    20
c    30
dtype: int64

In [71]:
#DataFrame

#create a DataFrame from Dictionary

data = {
    'Name':['AK','PP','Krish'],
    'Age': [21,21,33],
    'City': ['Cincinnati','Denver','Banglore']
}
df = pd.DataFrame(data)
print(df)

    Name  Age        City
0     AK   21  Cincinnati
1     PP   21      Denver
2  Krish   33    Banglore


In [98]:
data2 = [
    {'Name':'AK','Age':21,'City':'Cincinnati'},
    {'Name':'PP','Age':21,'City':'Denver'},
    {'Name':'Krish','Age':33,'City':'Banglore'}
]
df2 = pd.DataFrame(data2)
print(df2)

    Name  Age        City
0     AK   21  Cincinnati
1     PP   21      Denver
2  Krish   33    Banglore


In [99]:
df2['Name']


0       AK
1       PP
2    Krish
Name: Name, dtype: object

In [100]:
df2.loc[0]

Name            AK
Age             21
City    Cincinnati
Name: 0, dtype: object

In [101]:
df2.iloc[1]

Name        PP
Age         21
City    Denver
Name: 1, dtype: object

In [102]:
df2.at[1,'Age']

np.int64(21)

In [103]:
df2.iat[2,2]

'Banglore'

In [104]:
#Adding a column
df2['Salary'] = [50000,60000,70000]
df2

In [105]:
df2.drop('Salary',axis = 1,inplace=True)

In [106]:
df2

Name  Age        City
0     AK   21  Cincinnati
1     PP   21      Denver
2  Krish   33    Banglore

In [ ]:
read_csv_data = pd.read_csv("FILE_PATH")
read_csv_data.head(10)