# Numpy in Python

In [3]:
  #Create 1D array

import numpy as np

arry = np.array([1, 2, 3, 4, 5])
print(arry)
print(type(arry))
print(arry.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [5]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [6]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2.shape

(2, 5)

In [7]:
array3 = np.arange(0,10,2).reshape(5,1)
array3

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
array3.dtype

dtype('int64')

In [12]:
array3.itemsize

8

In [13]:
array3.ndim

2

In [14]:
array3.size

5

In [21]:
# Numpy Vectorized Operations

array1 = np.array([1,2,3,4,5])
array2 = np.array([10,20,30,40,50])

print ("Addition:", array1 + array2)


#Element wise opeartions

print ("Substraction:", array1 - array2)
print ("Multiplication:", array1 * array2)
print ("Division:", array1 / array2)



Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [24]:
#universal function

print("Square root:" ,np.sqrt(array2))
print("Exponent:" ,np.exp(array2))
print("Sin:" ,np.sin(array2))

Square root: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
Exponent: [2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
Sin: [-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]


In [44]:
# Array Slicing and Indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n", arr )
print(arr[0][2],arr[2][3])


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3 12


In [45]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [47]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [48]:
#Modify array elements

arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [49]:
#Modify array elements

arr[0,1:] = 100
print(arr)

[[100 100 100 100]
 [  5   6   7   8]
 [  9  10  11  12]]


In [52]:
#Statistical concepts - Normalization

data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data -  mean)/ std_dev

print("Normalized Data: ", normalized_data)

Normalized Data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [53]:
median = np.median(data)
variance = np.var(data)

 #Logical operations

data2 = np.array([1,2,3,4,5,6,7,8,9,10])
data2[(data2>=5) & (data2<=8)]

# PANDAS- DataFrame and Series

In [61]:
 import pandas as pd

In [62]:
# Series 1D-array that can hold any datatype

data = [1,2,3,4,5]
series = pd.Series(data)
print("Series \n",series)

Series 
 0    1
1    2
2    3
3    4
4    5
dtype: int64


In [63]:
#Create a series from dictionary
data_dict = {'a':1,'b':2,'c':3}
series_dict = pd.Series(data_dict)
print(series_dict)

a    1
b    2
c    3
dtype: int64


In [65]:
data = [10,20,30]
index = ['a','b','c']

pd.Series(data,index=index)


a    10
b    20
c    30
dtype: int64

In [71]:
#DataFrame

#create a DataFrame from Dictionary

data = {
    'Name':['AK','PP','Krish'],
    'Age': [21,21,33],
    'City': ['Cincinnati','Denver','Banglore']
}
df = pd.DataFrame(data)
print(df)

    Name  Age        City
0     AK   21  Cincinnati
1     PP   21      Denver
2  Krish   33    Banglore


In [98]:
data2 = [
    {'Name':'AK','Age':21,'City':'Cincinnati'},
    {'Name':'PP','Age':21,'City':'Denver'},
    {'Name':'Krish','Age':33,'City':'Banglore'}
]
df2 = pd.DataFrame(data2)
print(df2)

    Name  Age        City
0     AK   21  Cincinnati
1     PP   21      Denver
2  Krish   33    Banglore


In [99]:
df2['Name']


0       AK
1       PP
2    Krish
Name: Name, dtype: object

In [100]:
df2.loc[0]

Name            AK
Age             21
City    Cincinnati
Name: 0, dtype: object

In [101]:
df2.iloc[1]

Name        PP
Age         21
City    Denver
Name: 1, dtype: object

In [102]:
df2.at[1,'Age']

np.int64(21)

In [103]:
df2.iat[2,2]

'Banglore'

In [104]:
#Adding a column
df2['Salary'] = [50000,60000,70000]
df2

In [105]:
df2.drop('Salary',axis = 1,inplace=True)

In [106]:
df2

Name  Age        City
0     AK   21  Cincinnati
1     PP   21      Denver
2  Krish   33    Banglore

In [ ]:
read_csv_data = pd.read_csv("FILE_PATH")
read_csv_data.head(10)

# Data Manupulation and Analysis with Pandas

In [42]:
import pandas as pd

In [43]:
df  = pd.read_csv("sales_data.csv") 

In [44]:
df.head(10)

Group Customer_Segment  Sales_Before  Sales_After  \
0    Control       High Value    240.548359   300.007568   
1  Treatment       High Value    246.862114   381.337555   
2    Control       High Value    156.978084   179.330464   
3    Control     Medium Value    192.126708   229.278031   
4        NaN       High Value    229.685623          NaN   
5  Treatment              NaN    135.573003   218.559988   
6    Control       High Value    191.713918   222.409356   
7    Control        Low Value    173.752555   213.168232   
8        NaN       High Value    208.308577   248.178830   
9  Treatment       High Value    235.071493   352.756872   

   Customer_Satisfaction_Before  Customer_Satisfaction_After Purchase_Made  
0                     74.684767                          NaN            No  
1                    100.000000                   100.000000           Yes  
2                     98.780735                   100.000000            No  
3                     49.333766                    39.811841           Yes  
4                     83.974852                    87.738591           Yes  
5                     58.075342                    69.404918            No  
6                     89.967827                    85.120975           Yes  
7                     66.984711                    67.881558           NaN  
8                     95.366670                    84.790294           Yes  
9                     72.919851                    70.753225            No

In [45]:
df.tail(5)

Group Customer_Segment  Sales_Before  Sales_After  \
9995  Treatment              NaN    259.695935   415.181694   
9996    Control       High Value    186.488285   216.225457   
9997  Treatment        Low Value    208.107142   322.893351   
9998  Treatment     Medium Value           NaN   431.974901   
9999    Control        Low Value           NaN   124.402398   

      Customer_Satisfaction_Before  Customer_Satisfaction_After Purchase_Made  
9995                     88.438776                    98.418593           NaN  
9996                     92.261537                   100.000000           NaN  
9997                     55.915870                          NaN            No  
9998                     66.082462                    81.274030            No  
9999                     55.692277                    65.288480           Yes

In [46]:
df.describe()

Sales_Before  Sales_After  Customer_Satisfaction_Before  \
count   8478.000000  9233.000000                   8330.000000   
mean     203.716998   280.457952                     70.252076   
std       55.273059    85.659543                     16.957010   
min       24.852966    32.414352                     22.202441   
25%      166.629232   221.436990                     56.365513   
50%      203.323607   273.129170                     69.490898   
75%      238.809147   332.570108                     83.426798   
max      545.422547   818.219997                    100.000000   

       Customer_Satisfaction_After  
count                  8360.000000  
mean                     73.872593  
std                      18.128351  
min                      18.224938  
25%                      59.925030  
50%                      73.844594  
75%                      90.044365  
max                     100.000000

In [47]:
df.dtypes

Group                            object
Customer_Segment                 object
Sales_Before                    float64
Sales_After                     float64
Customer_Satisfaction_Before    float64
Customer_Satisfaction_After     float64
Purchase_Made                    object
dtype: object

In [48]:
df.shape

(10000, 7)

In [49]:
#Handling missing values
df.isnull().sum()

Group                           1401
Customer_Segment                1966
Sales_Before                    1522
Sales_After                      767
Customer_Satisfaction_Before    1670
Customer_Satisfaction_After     1640
Purchase_Made                    805
dtype: int64

In [50]:
df['Sales_Before'] = df['Sales_Before'].fillna(df['Sales_Before'].mean())
df=df['Sales_After'] = df['Sales_After'].fillna(df['Sales_After'].mean())
df['Customer_Satisfaction_Before'] = df['Customer_Satisfaction_Before'].fillna(df['Customer_Satisfaction_Before'].mean())
df['Customer_Satisfaction_After'] = df['Customer_Satisfaction_After'].fillna(df['Customer_Satisfaction_After'].mean())

In [51]:
df.head(10)

Group Customer_Segment  Sales_Before  Sales_After  \
0    Control       High Value    240.548359   300.007568   
1  Treatment       High Value    246.862114   381.337555   
2    Control       High Value    156.978084   179.330464   
3    Control     Medium Value    192.126708   229.278031   
4        NaN       High Value    229.685623   280.457952   
5  Treatment              NaN    135.573003   218.559988   
6    Control       High Value    191.713918   222.409356   
7    Control        Low Value    173.752555   213.168232   
8        NaN       High Value    208.308577   248.178830   
9  Treatment       High Value    235.071493   352.756872   

   Customer_Satisfaction_Before  Customer_Satisfaction_After Purchase_Made  
0                     74.684767                    73.872593            No  
1                    100.000000                   100.000000           Yes  
2                     98.780735                   100.000000            No  
3                     49.333766                    39.811841           Yes  
4                     83.974852                    87.738591           Yes  
5                     58.075342                    69.404918            No  
6                     89.967827                    85.120975           Yes  
7                     66.984711                    67.881558           NaN  
8                     95.366670                    84.790294           Yes  
9                     72.919851                    70.753225            No

In [52]:
df.isnull().sum()

Group                           1401
Customer_Segment                1966
Sales_Before                       0
Sales_After                        0
Customer_Satisfaction_Before       0
Customer_Satisfaction_After        0
Purchase_Made                    805
dtype: int64

In [57]:
# Renaming columns
df = df.rename(columns = {'Group':'Category'})

In [58]:
#changing data type float ---> int
df['sales_final'] = df['Sales_After'].round().astype(int)
df['customer_satisfaction_final'] = df['Customer_Satisfaction_After'].round().astype(int)

In [63]:
#Data Aggregating and Grouping

grouped_mean = df.groupby('Category')['Sales_After'].mean()
print(grouped_mean)

Category
Control      246.230167
Treatment    315.310479
Name: Sales_After, dtype: float64


In [65]:
df.groupby(['Category','Purchase_Made'])['Sales_After'].sum()

Category   Purchase_Made
Control    No               483939.011649
           Yes              488493.724374
Treatment  No               606696.905257
           Yes              641801.333603
Name: Sales_After, dtype: float64

In [66]:
df.groupby(['Category','Purchase_Made'])['Sales_After'].mean()

Category   Purchase_Made
Control    No               248.301186
           Yes              244.491354
Treatment  No               314.025313
           Yes              316.314112
Name: Sales_After, dtype: float64

In [69]:
#Aggregate multiple fuctions

grouped_agg = df.groupby('Category')['Sales_After'].agg(['sum','mean','count'])
grouped_agg

sum        mean  count
Category                                  
Control    1.058790e+06  246.230167   4300
Treatment  1.355520e+06  315.310479   4299

In [98]:
# Merging and Joining dataFrames
df1 = pd.DataFrame({'Key':['A','B','C'],'Value1':[1,2,3]})
df2 = pd.DataFrame({'Key':['A','B','E'],'Value2':[4,5,6]})

In [99]:
pd.merge(df1,df2,on='Key',how='inner')

Key  Value1  Value2
0   A       1       4
1   B       2       5

In [100]:
pd.merge(df1,df2,on='Key',how='outer')

Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   E     NaN     6.0

In [101]:
pd.merge(df1,df2,on='Key',how='left')

Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [102]:
pd.merge(df1,df2,on='Key',how='right')

Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   E     NaN       6

# Reading Data From different sources

In [2]:
import pandas as pd
from io import StringIO

In [3]:
Data = '{"employee_name":"James","email":"james@gmail.com","job_profile":[{"title1": "Team Lead","title2":"Sr. Developer"}]}'

In [4]:
df = pd.read_json(StringIO(Data))
df

employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr. Develop...

In [5]:
df.to_json(orient='index')

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [6]:
df.to_json(orient='records')

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [18]:
url = "https://www.fdic.gov/bank-failures/failed-bank-list/"
df_hmtl = pd.read_html(url)

In [19]:
df_html

[                               Bank Name               City         State  \
 0                   Pulaski Savings Bank            Chicago      Illinois   
 1     The First National Bank of Lindsay            Lindsay      Oklahoma   
 2  Republic First Bank dba Republic Bank       Philadelphia  Pennsylvania   
 3                          Citizens Bank           Sac City          Iowa   
 4               Heartland Tri-State Bank            Elkhart        Kansas   
 5                    First Republic Bank      San Francisco    California   
 6                         Signature Bank           New York      New York   
 7                    Silicon Valley Bank        Santa Clara    California   
 8                      Almena State Bank             Almena        Kansas   
 9             First City Bank of Florida  Fort Walton Beach       Florida   
 
     Cert                Acquiring Institution      Closing Date  \
 0  28611                      Millennium Bank  January 17, 2025   
 1  

In [49]:
url2= 'https://en.wikipedia.org/wiki/List_of_highest-grossing_films'
movie_records = pd.read_html(url2,match='Rank',header=0)[0]
movie_records.to_csv("movies_gross_rank.csv",index=False)

In [ ]:
# pd.to_pickle / read_pickle 